apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: dummy-api-route
spec:
  http:
  - name: dummy-api
    match:
      hosts:
      - test.api.org
      paths:
      - /*
    backends:
    - serviceName: dummy-api-svc
      servicePort: 80
