apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-api
  labels:
    app.kubernetes.io/name: go-rest-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: go-rest-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: go-rest-api
    spec:
      containers:
        - name: go-rest-api
          image: chentex/go-rest-api
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
            name: api-port
            protocol: TCP
