apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: apisix-monitor
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: apisix
  endpoints:
  - port: prometheus
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ingress-apisix-monitor
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-controller
  endpoints:
  - port: http
